key.type.pem_public:
  type: key.type.encryption
  label: 'Public .pem key type settings'

key.type.pem_private:
  type: key.type.encryption
  label: 'Private .pem key type settings'
  mapping:
    passphrase:
      type: string
      label: 'Key Passphrase'